# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_QTI_MPAM) += mpam.o
obj-$(CONFIG_QTI_CPU_MPAM_INTERFACE) += cpu_mpam.o
obj-$(CONFIG_QTI_PLATFORM_MPAM_INTERFACE) += platform_mpam.o
obj-$(CONFIG_QTI_MPAM_MSC) += mpam_msc.o
obj-$(CONFIG_QTI_MPAM_MSC_SLC) += mpam_msc_slc.o
obj-$(CONFIG_QTI_SLC_MPAM_INTERFACE) += slc_mpam.o
