dtb-y += pa3q_eur_openx_w00_r11.dtbo
dtb-y += pa3q_eur_openx_w00_r10.dtbo
dtb-y += pa3q_eur_openx_w00_r08.dtbo
dtb-y += pa3q_eur_openx_w00_r05.dtbo
dtb-y += pa3q_eur_openx_w00_r04.dtbo
dtb-y += pa3q_eur_openx_w00_r03.dtbo
dtb-y += pa3q_eur_openx_w00_r02.dtbo
dtb-y += pa3q_eur_openx_w00_r01.dtbo
# SPDX-License-Identifier: GPL-2.0
# COPYRIGHT(C) 2023 Samsung Electronics Co., Ltd. All Right Reserved.

# TODL: remove the below sub-makefile after lego is enabled.
# ne3q_dir		:= $(srctree)/$(src)
# include $(ne3q_dir)/without_lego.mk

